- st2installer/controllers/root.py
Use full path to kick off Puppet
> Update Puppet Run

- st2installer/controllers/root.py
Makes it possible for StackStorm to be fully functional in `st2workroom`.
> Workroom fixes

- public/scripts/main.js
- setup.py
- st2installer/controllers/root.py
- st2installer/templates/progress.html
- test/output.py
Reverts StackStorm/st2installer#3
> Revert "Locking the installer"

- st2installer/templates/index.html
This PR updates the installation language for a few of the steps in Installation. This is based on feedback for approval to AWS Marketplace
> Update language for installation steps

- st2installer/controllers/root.py
- st2installer/templates/index.html
Pulls in #8 and #9 to `stable` branch.
> Cherry-Picked Commits

- README.md
- public/scripts/main.js
- setup.py
- st2installer/controllers/root.py
- test/output.py
1. Some very minor fixes for ChatOps;
2. uWSGI dependency;
3. Installation manual (this one is long overdue).
> Help and fixes

- st2installer/templates/index.html
This PR adds better verbiage around setting the system hostname in the installer.
> provide better clarification around hostname

- public/scripts/main.js
- public/stylesheets/main.css
- st2installer/controllers/keypair.py
- st2installer/controllers/root.py
- st2installer/templates/index.html
1. Default "hostname" field to server host.
2. "Download" buttons for SSH keys.
> Minor fixes

- requirements.txt
`pip freeze` of installed requirements.
> adding requirements for virtualenv

- st2installer/templates/index.html
Some words are missing. Trying one more time.
> Update wording on installer

- st2installer/controllers/root.py
> SSH keypair upload fix

- public/scripts/main.js
Fixes #26
Another method of complexity validation: instead of validating the whole input against a regex we’ll separately check if it has at least one letter and at least one digit, exactly as it says in the hint:
> 8+ alphanumeric characters, at least one digit and one letter is required.
> Password validation fix

- st2installer/controllers/root.py
> Granting access to config file with sudo

- public/scripts/main.js
- public/stylesheets/main.css
- st2installer/controllers/root.py
- st2installer/templates/layout.html
- st2installer/templates/progress.html
Checked CA on my local st2express, everything works, yay.
> Merging everything into stable

- st2installer/templates/index.html
Disables the default checked value for 'Send anonymous data'
> Disable check-box for anonymous data

- public/scripts/main.js
- st2installer/templates/layout.html
More detailed pageviews and the sending of custom metrics.
Still not sure it will work as planned, but let’s test.
> Google Analytics fine-tuning

- public/scripts/main.js
- st2installer/controllers/root.py
- st2installer/templates/progress.html
1. Adding more metrics to allow for finer granularity in Google Analytics panel
2. Changing the pageviews to show a proper user flow.
3. Fixing errors.
> Further analytics enhancements

- config.py
Reverts StackStorm/st2installer#79
> Revert "Disable debug in prod config"

- st2installer/templates/layout.html
Support all the installs!
We don’t have a dedicated KB section on the installer just yet, but at least it will be useful to get in touch.
> re:Amaze widget

- public/scripts/main.js
- st2installer/templates/index.html
It’s not even implemented anyway.
> Removing the "local IRC" option

- st2installer/controllers/root.py
Check out https://github.com/StackStorm/puppet-st2/blob/master/manifests/stanley.pp#L28
> Fix stanley::ssh_*_key dictionary key

- st2installer/controllers/root.py
Fixes https://github.com/StackStorm/st2/issues/2327
Reported by @partkyle at Slack community.
> Escaping special chars in Hubot env params
