- public/scripts/main.js
- setup.py
- st2installer/controllers/root.py
- st2installer/templates/progress.html
- test/output.py
1. The installer is locked right after puppet has started: every page request redirects into the installation page so that configuration can't be changed after puppet starts.
2. There's a cleanup hook to remove the installer after puppet has finished.
> Locking the installer

- st2installer/controllers/root.py
This commit adds three variables, `ST2_API`, `ST2_AUTH_URL`, and `ST2_WEBUI_URL` to the auto-generated answers file. This is needed to authenticate hubot.
> Add `ST2_API` and `ST2_AUTH_URL` to answers file.

- st2installer/controllers/root.py
Need to check for existence of key in the dict, otherwise bombs out with 
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/pecan/middleware/debug.py", line 289, in __call__
return self.app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/pecan/middleware/recursive.py", line 56, in __call__
return self.application(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/pecan/middleware/errordocument.py", line 75, in __call__
app_iter = self.app(environ, replacement_start_response)
File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 762, in __call__
return super(Pecan, self).__call__(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 625, in __call__ …
```
> needs to check for key in dict for anon-data upload

- st2installer/controllers/root.py
- st2installer/templates/index.html
This PR makes the freshly created admin account a configurable value at boot to reduce confusion for new users.
> Make admin account configurable

- public/scripts/main.js
- public/stylesheets/main.css
- st2installer/templates/layout.html
- st2installer/templates/progress.html
Fixes #29
If a root CA is present (we’re checking `/ssl/st2_root_ca.cer` with a HEAD request), display a warning about installing it with a link to wiki and the certificate itself.
> Show RootCA warning if a CA is generated and accessible

- st2installer/controllers/root.py
* is_locked is useful only after lock is called. Lock
is not called until much later and reverting back to
config_written is better. This may not actually be the
right fix but it does unblock the DOA build.
> Use config_written instead of is_locked

- requirements.txt
- st2installer/controllers/root.py
* Using IP  instead of hostname causes much pain an misery so replacing
. and : with hyphen.
> Replace "." and ":" with hyphen incase provided value is an IP

- st2installer/controllers/root.py
This commit updates the `pgrep` check to look for the actual process called (`puppet-apply`), and parsing the entire procline.
> Update puppet-check with full pgrep flag

- public/scripts/main.js
- st2installer/controllers/root.py
- st2installer/templates/layout.html
- st2installer/templates/progress.html
Google Analytics wiring:
1. Basic page tracking (regarding tabs as separate pages so we can track how much time does it take to complete each)
2. Puppet runtime tracking
3. Chatops back-end: enabled/disabled, backend
4. SSH/SSL tracking: generated/uploaded, self-signed/uploaded
I created all the necessary metrics and dimensions inside the StackStorm GA account as well. 
Note: right now the data doesn’t show up in GA, __don’t merge__ until I figure out what’s going on. Browser is able to send requests, I can see the beacons, I checked that the right data gets sent, but nothing shows up in Google Analytics panel.
Probably it’s connected to the fact we’re running Installer in intranet without a permanent domain, but I do know that it’s possible. Some people warn that for intranet data to …
> [WIP] Analytics

- public/scripts/main.js
- st2installer/controllers/keypair.py
- st2installer/tests/test_functional.py
This pull request updates KeyPair controller to create SSH key pair on demand instead of generating it inside the constructor and leaving it hanging in the memory...
In addition to that, it implements "download key as file" functionality on the client side so we don't need to leave key hanging in memory. If we want to use old approach, but do it more securely we would need to implement some kind of session mechanism, but this is a big over kill since we can just handle it with JavaScript (all modern browsers support this functionality).
> Generate SSH key pair on demand, download it using JavaScript

- config.py
- public/scripts/main.js
- public/stylesheets/main.css
- st2installer/controllers/keypair.py
- st2installer/controllers/root.py
- st2installer/templates/index.html
- st2installer/templates/progress.html
- st2installer/tests/test_functional.py
- st2installer/tests/test_units.py
- test/output.py
- tox.ini
1. "StackStorm Enterprise" section in the first tab:
Checkbox state is written to "st2enterprise::token": if checked, `get_enterprise_token` method is evaluated; if not, an empty string is passed.
2. Installation progress page rework: a bit more love to the links and some minor changes.
3. Lots of linting: python is linted with `flake8`, js is linted with `jshint`.
Change as necessary: I think the wording has to be adjusted on the progress page. Also, I tried to make a separate "after install" page and found the experience a bit strange, so I just reworked links and element order instead. I think what we have now is good.
I'm also not sure if I have to write an empty string to "st2enterprise::token" or just don't have that key in config at all.
Lastly, @jfryman asked me to put a message …
> Enterprise modifications

- README.md
- config.py
- st2installer/templates/index.html
- st2installer/tests/config.py
As @dzimine requested, making license key disabled by default to avoid confusion.
Also, clarified the readme for the versioning system to make things a bit more clear.
> Making license key field disabled by default

- config.py
We should only enable debug for local development - we can do that using a separate config for a local development.
> Disable debug in prod config

- public/scripts/main.js
- st2installer/controllers/root.py
1. Restart docker-hubot from cleanup
2. Calling cleanup when puppet is done regardless of what happens in the UI
3. Chaining cleanup commands instead of executing in parallel
4. Outputting cleanup errors into the console
> Reimplementing cleanup logic

- st2installer/templates/progress.html
Toned down the message a bit, because the CA is advised rather than required now that we have single-port deployment.
> A milder CA message

- st2installer/controllers/root.py
- st2installer/templates/progress.html
One issue we had starting from, um, I don’t even know when is being unable to access the installer page after the install is done. That’s a regression, because it wasn’t like this at the beginning, but I guess nobody just cared much. :P
This PR fixes it: when you refresh the installer or open another install page in parallel, you’ll get the same log, and nothing will be run twice. When you open the installer after everything’s done, you’ll get the success message and the full log.
This is a pre-req to fixing the UI being unable to tell when the install is complete in some cases.
> Fixing the redirect loop

- public/scripts/main.js
This PR solves the problem of installer not being able to finish, because the HTTPS certificate changes mid-flight and the logs can’t be accessed anymore, which means there’s no indication of install finishing.
Now the UI reloads on five consecutive log access errors. In case with certificate changing this would mean that the user will be prompted to accept a new cerificate on reload, and the install will continue.
Needs #90 to ensure smooth continuation.
> Reload the page on consecutive access errors

- st2installer/controllers/root.py
Reported by @stuartwhelan on the community channel.
`btf.hipchat.com` is the only correct value regardless of the domain a user has.
> Correct HipChat Server settings

- st2installer/controllers/root.py
There is a weird bug with puppet and GUI installer where the system doesn't fully converge on the initial puppet run.
Initially we thought this is only related to RBAC since this is one of the things which doesn't fully converge on the initial run, but it turns out there are other things which only fully converge on second run (pack permissions, setting postgres password, etc.).
We haven't been able to track down and fix the root cause and bug yet so we are left with the best option we have so far. That is a work around which includes running `puprun` inside the installer loop twice.
"Good" news is that in theory you could run puprun as many times as you want and as long as you use the same code and answer.json files the result should be the same (well, the whole cfg management and …
> Fix for the convergence bug (run puppet twice)

- scripts/run-puppet.sh
- st2installer/controllers/root.py
Using script makes it easier for us to add logging, etc.
In addition to that, I added support for debug.
> Use a script to run puppet and add support for debug

- st2installer/controllers/root.py
* this assumption is clearly spelled out in the docs and ssh_key_type is required
as per https://github.com/StackStorm/puppet-st2/blob/5c4a3fcf66e69853136cabb62aa5ca365033022c/manifests/user.pp#L72
> hardcode ssh_key_type to ssh-rsa

- public/scripts/main.js
Today’s best effort at fixing the dreadful Installer Redirect Loop. This is a multi-part fix:
1. Apparently different browsers treat “insecure response” differently, and refreshing with `force` flag makes things slightly better.
2. We terminate polling altogether once the critical number of errors has been reached. This was the main cause of the loop: if the refresh takes longer than a second, another polling takes place and another refresh starts before the previous one could execute. This is dead simple, but forced reloads was the thing that actually helped me reliably track this.
3. There is an issue when nginx+installer reload actually takes longer than 5 seconds. That’s what happens in this case: a redirect fires, a blank log screen shows up, then times out, then another redirect …
> Force reload: fix redirect loop

- st2installer/controllers/root.py
Reverts StackStorm/st2installer#95
Escaping env variable at that point does not fixes the problem with special characters instead introduces another one related to the quotes which breaks hipchat adapter in different ways. The right way to do the escaping would be to quote every env variable in workroom at the point the command is constructed.
> Revert "Escaping special chars in Hubot env params"

- st2installer/controllers/root.py
Add `ST2_HOSTNAME` for compatibility with the new container having
`st2chatops.env`.
> Add hostname into Hubot's env variables
